#ifndef ZB2_CORE_CARGA_BAR_H
#define ZB2_CORE_CARGA_BAR_H

// Leitor do formato `.bar` -- os RECURSOS do BREW (IShell::LoadResDataEx).
//
// O formato foi MEDIDO, e nao transcrito de nenhum emulador. As medicoes estao
// aqui, uma a uma, com o comando que as produz (P1). O comando que as refaz:
//
//     python3 tools/medir_bar.py censo "<SDK>" "<mods>/276212/pacmania.bar"
//     python3 tools/medir_bar.py recurso "<mods>/276212/pacmania.bar" 6 5091
//     python3 tools/medir_bar.py desmontar "<mods>/276212/pacmania.mod" 0x110d8c 0x120
//
// (`<mods>` = /media/rafaelfrequiao/8C5F-19E51/zeebo/ROMs/debug_nand/mod,
//  `<SDK>`  = research/docs/sdk-extract/BrewMPSDK-7.12.5/SDKPro/1.0.4.601 Pro)
//
// ---------------------------------------------------------------------------
// 1) Cabecalho, 32 bytes, little-endian
// ---------------------------------------------------------------------------
//
//   u16  versao               @0   0x0011. Medido em 320 de 320 `.bar` do SDK e
//                                   no `pacmania.bar` (bytes `11 00`).
//   u16  campo_2              @2   1. Medido em 320 de 320.
//   u16  campo_4              @4   1. Medido em 320 de 320.
//   u16  num_registos         @6   numero de registos de 8 bytes que seguem.
//   u32  deslocamento_registos@8   32 = 0x20. Medido em 320 de 320 e no pacmania.
//   u32  tamanho_registos     @12  == 8 * num_registos.
//   u32  deslocamento_indices @16  == deslocamento_registos + tamanho_registos.
//   u32  num_ids              @20  numero de pares (tipo, id) resolviveis;
//                                   == soma, por registo, de (delta + 1).
//   u32  deslocamento_dados   @24  inicio da zona de dados; igual ao PRIMEIRO
//                                   valor da tabela de indices.
//   u32  campo_28             @28  NAO e o tamanho dos dados. No `pacmania.bar`
//                                   vale 7454921 e off(24)+7454921 == tamanho do
//                                   ficheiro, mas a soma falha em 8 dos 320
//                                   `.bar` do SDK. Nao se usa para nada: o
//                                   tamanho do ficheiro e o ULTIMO valor da
//                                   tabela de indices, e isso vale em 320 de 320.
//
// Numeros do `pacmania.bar` (7455569 bytes), lidos com
// `xxd -l 32 <ficheiro>` e `python3 tools/medir_bar.py`:
//   versao=0x0011 campos=(1,1) num_registos=5 off_regs=32 tam_regs=40
//   off_indices=72 num_ids=143 off_dados=648 campo_28=7454921.
//
// ---------------------------------------------------------------------------
// 2) Registos de 8 bytes: o DIRECTORIO (tipo, id) -> indice
// ---------------------------------------------------------------------------
//
//   u16 tipo; u16 primeiro_id; u16 delta; u16 primeiro_indice;
//
//   O registo declara um INTERVALO CONTIGUO: os ids [primeiro_id,
//   primeiro_id + delta], delta+1 ids, resolvem para os recursos de indice
//   [primeiro_indice, primeiro_indice + delta].
//
// A prova de que `delta` e um delta (e nao uma contagem) e um cabecalho gerado
// pelo VENDEDOR, nao uma deducao minha:
//   `.../aeecontrols.bar` (locale `es`) traz os registos
//   (tipo=6, id=1, delta=15, indice=0) e (tipo=1, id=1, delta=50, indice=16),
//   e `platform/deprecated/inc/AEEControls_res.h` -- "AUTO-GENERATED BY BREW
//   Resource Editor" -- declara exactamente 16 bitmaps (`AEE_IDB_*`, 1..16) e
//   51 `strings` (`AEE_IDS_*`, 1..51). Com delta: 16 + 51 = 67 = num_ids do
//   cabecalho (medido). Com contagem: 15 + 50 = 65, e um bitmap a menos do que
//   o cabecalho do vendedor declara. `tools/medir_bar.py censo` confere a soma
//   em todos os `.bar` dados.
//
// E o conteudo confirma o mesmo em `es`: indice 0 = AEEResBlob com mime
// `image/bmp` e um BMP dentro (id 1, tipo 6 = RESTYPE_IMAGE); indice 16 = o
// texto `03 "enero"`, e `AEEControls_res.h` diz `AEE_IDS_JANUARY = 1`.
//
// Os 5 registos do `pacmania.bar` (bytes, com `xxd -s 32 -l 40`):
//   (6, 5001, 117,   0)
//   (6, 5120,   0,  76)
//   (6, 5121,   5, 119)
//   (6, 5127,   0,  10)
//   (6, 5128,  16, 126)
// Soma de (delta+1) = 143 = num_ids do cabecalho. Os dois registos de delta 0
// reutilizam um indice ja usado pelo primeiro (76 e 10 caem dentro de 0..117):
// dois ids podem apontar para o MESMO recurso. Os indices 118 e 125 nao sao
// referenciados por id nenhum.
//
// ---------------------------------------------------------------------------
// 3) Tabela de indices: num_ids + 1 valores u32
// ---------------------------------------------------------------------------
//
// Deslocamentos ABSOLUTOS no ficheiro, nao decrescentes. O valor [0] e o inicio
// dos dados e o ultimo e o TAMANHO DO FICHEIRO -- medido em 320 de 320 `.bar`
// do SDK (nao so no pacmania). O recurso `i` e `ficheiro[valor[i] .. valor[i+1])`.
// No `pacmania.bar`: valor[0]=648 (== off_dados), valor[143]=7455569, e a tabela
// e estritamente crescente excepto dois pares iguais (118 e 125), que sao
// recursos de tamanho ZERO.
//
// ---------------------------------------------------------------------------
// 4) O recurso e um `AEEResBlob` quando o tipo pedido e 6 (RESTYPE_IMAGE)
// ---------------------------------------------------------------------------
//
// `platform/deprecated/inc/AEEShell.h`, a seguir a `LoadResDataEx`:
//
//   typedef struct AEEResBlob { byte bDataOffset; byte bZero; char szMimeType[1]; };
//
// com `bDataOffset` = onde comeca o dado a serio, `bZero` = sempre zero, e o
// mime terminado em NUL. O `pacmania` nao segue a documentacao por fe: ele LE
// esta struct do ponteiro devolvido. Desmontado com capstone (comando
// `desmontar` acima), no `pacmania.mod`, logo depois da chamada ao slot 41:
//
//   00110dcc  ldrb r0, [r5]        ; r5 = ponteiro devolvido por LoadResDataEx
//   00110dd4  add  r1, r5, r0      ; r1 = blob + bDataOffset
//   00110dd8  ldrb r0, [r1]        ; e daqui le os campos do dado
//   00110de0  ldrb r0, [r1, #1]
//   00110de8  ldrb r0, [r1, #2]
//   00110df8  ldrb r0, [r1, #3]
//   00110df0  ldrb r0, [r1, #5]    ; o maior deslocamento que ele le: 5
//
// E o recurso que ele pede ali tem, medido, EXACTAMENTE 6 bytes de dado:
//   indice 90 -> ficheiro[6234497 .. 6234531) = 34 bytes
//   `1c 00 61 70 70 6c 69 63 61 74 69 6f 6e 2f 6f 63 74 65 74 2d 73 74 72 65 61 6d 00 00
//    01 00 14 36 1e f0`
//   bDataOffset = 0x1c = 28; mime = "application/octet-stream"; dado = 6 bytes.
//
// ---------------------------------------------------------------------------
// 5) A assinatura, lida do cabecalho do SDK (e nao de mim)
// ---------------------------------------------------------------------------
//
// `platform/system/inc/AEEIShell.h`, INHERIT_IShell:
//
//   void* (*LoadResDataEx)(iname *po, const char *pszResFile, uint16 nResID,
//                          ResType nType, void *pBuf, uint32 *pnLen);
//
// `pszResFile` e o NOME DO FICHEIRO -- o jogo passa a cadeia "pacmania.bar"
// (medida: a cadeia esta em 0x00101a64 do `pacmania.mod`, e o campo +0x120 do
// applet guarda esse ponteiro), nao os dados. Slot 41, gerado de
// `AEEIShell.h` por `tools/gerar_slots.py` -> `tools/brew_slots.inc`.
//
// O contrato de `pBuf`, do mesmo cabecalho:
//   `#define ISHELL_GetResSize(p,psz,id,t,l) (IShell_LoadResDataEx((p),(psz),(id),(t),(void *)-1,(l)),*l)`
//   -> `pBuf == (void*)-1` significa "so quero o tamanho", em `*pnLen`.
// E o `pacmania` chama com `pBuf = NULL` (medido no desmonte acima:
// `mov r2, #0` / `strd r2, r3, [sp]`, com `r3 = sp+8`), esperando um ponteiro
// alocado por quem serve.
//
// ---------------------------------------------------------------------------
// O QUE ESTE MODULO NAO FAZ
// ---------------------------------------------------------------------------
//
// Nao serve o slot 41, nao aloca memoria do guest e nao conhece o `IShell`: quem
// liga isto ao despacho e o despacho. Aqui le-se o ficheiro e recusa-se em voz
// alta o que nao bate certo com a medicao acima.

#include <cstdint>
#include <string>
#include <vector>

namespace zb2 {

// Um registo do directorio. Os nomes sao os da medicao da seccao 2 do cabecalho.
struct RegistroDoBar {
  std::uint16_t tipo = 0;
  std::uint16_t primeiro_id = 0;
  std::uint16_t delta = 0;
  std::uint16_t primeiro_indice = 0;

  std::uint16_t UltimoId() const {
    return static_cast<std::uint16_t>(primeiro_id + delta);
  }
  std::uint16_t UltimoIndice() const {
    return static_cast<std::uint16_t>(primeiro_indice + delta);
  }
};

// Um recurso lido. `dados` APONTA PARA DENTRO da memoria do `ArquivoBar` que o
// produziu -- nao ha copia, porque o `pacmania.bar` tem 7.455.569 bytes. O
// `ArquivoBar` tem de continuar vivo enquanto `dados` for usado.
struct RecursoDoBar {
  bool ok = false;
  std::string motivo;              // vazio quando ok
  const std::uint8_t* dados = nullptr;
  std::uint32_t tamanho = 0;
  std::uint32_t indice = 0;        // indice na tabela de deslocamentos
  std::uint16_t tipo = 0;
  std::uint16_t id = 0;
};

// O `AEEResBlob` da seccao 4, ja lido. `dados` aponta para o DADO, depois do
// mime (`RESBLOB_DATA` do SDK: `blob + bDataOffset`).
struct BlobDoBar {
  bool ok = false;
  std::string motivo;
  std::uint8_t deslocamento = 0;
  std::string mime;
  const std::uint8_t* dados = nullptr;
  std::uint32_t tamanho = 0;
};

class ArquivoBar {
 public:
  ArquivoBar() = default;

  // Le o ficheiro inteiro e valida-o. Um ficheiro que nao existe, que nao se
  // consegue ler, ou que nao bate certo com o formato MEDIDO, devolve um
  // `ArquivoBar` invalido com o motivo preenchido -- nunca um objecto "a fingir
  // de bom" (P2 do DESIGN.md).
  static ArquivoBar AbrirFicheiro(const std::string& caminho, std::string* motivo);

  // O caminho normal do emulador: os bytes vem da VFS, ja em memoria. Nao ha
  // I/O de ficheiro aqui, e portanto nao ha caminho relativo, nem ordem de
  // leitura dependente do sistema (P4).
  static ArquivoBar AbrirDados(std::vector<std::uint8_t> bytes, std::string* motivo);

  bool Valido() const { return valido_; }
  const std::string& Motivo() const { return motivo_; }
  std::uint32_t Tamanho() const { return static_cast<std::uint32_t>(bytes_.size()); }
  std::uint32_t NumeroDeRecursos() const { return numero_de_recursos_; }
  std::uint32_t NumeroDeIds() const { return numero_de_ids_; }
  const std::vector<RegistroDoBar>& Registros() const { return registros_; }
  const std::vector<std::uint32_t>& Deslocamentos() const { return deslocamentos_; }

  // Resolve (id, tipo) para um INDICE da tabela de deslocamentos, sem tocar nos
  // dados. Recusa com motivo quando o par nao esta em registo nenhum, ou quando
  // o registo aponta para fora da tabela.
  bool Procurar(std::uint16_t id, std::uint16_t tipo, std::uint32_t* indice,
                std::string* motivo) const;

  // O entregavel: o recurso, ou a recusa com motivo.
  RecursoDoBar Ler(std::uint16_t id, std::uint16_t tipo) const;

  // O recurso por indice directo (quem ja tem o indice do directorio).
  RecursoDoBar LerPorIndice(std::uint32_t indice) const;

  // Le o `AEEResBlob` de um recurso. Vale para os recursos de tipo 6
  // (RESTYPE_IMAGE); recusa o que nao tiver a forma da seccao 4.
  static BlobDoBar LerBlob(const RecursoDoBar& recurso);

 private:
  bool Validar();

  std::vector<std::uint8_t> bytes_;
  bool valido_ = false;
  std::string motivo_;
  std::uint32_t numero_de_recursos_ = 0;
  std::uint32_t numero_de_ids_ = 0;
  std::vector<RegistroDoBar> registros_;
  std::vector<std::uint32_t> deslocamentos_;
};

// Os nomes medidos no cabecalho (seccao 1). Ficam aqui para o teste os poder
// usar sem repetir numeros, e para a recusa poder dizer QUAL campo falhou.
namespace bar_campos {
constexpr std::uint16_t kVersao = 0x0011u;
constexpr std::uint16_t kCampo2 = 1u;
constexpr std::uint16_t kCampo4 = 1u;
constexpr std::uint32_t kCabecalho = 32u;
constexpr std::uint32_t kDeslocamentoDosRegistos = 32u;
constexpr std::uint16_t kTipoImagem = 6u;  // RESTYPE_IMAGE, de AEEShell.h
}  // namespace bar_campos

}  // namespace zb2

#endif  // ZB2_CORE_CARGA_BAR_H
